### ISSUE TITLE
Getting started with this package

### ISSUE THREAD

**Issue by hzarei4** [tex-persian/xepersian#13]
## Brief outline of the question

I just started using this package in Overleaf and I can use the commands `\textit` of `\textbf`. How can I implement and use these commands in persian document with XePersian?

Thanks,
## Check/indicate
- [ ] Relevant to the `bidi` package
- [ ] [The `bidi` package issue tracker](https://github.com/tex-persian/bidi/issues) has been searched for similar issues?
- [ ] [The `xepersian` package issue tracker](https://github.com/tex-persian/xepersian/issues) has been searched for similar issues?
- [ ] Links to <tex.stackexchange.com> discussion if appropriate
- [ ] Links to <qa.parsilatex.com> discussion if appropriate

## Minimal example

```tex
% !TEX TS-program = XeLaTeX
% !TEX encoding = UTF-8 Unicode


\documentclass{article}            % or some other class

  % Any packages other than the xepersian package must be loaded here

  % The xepersian package must be loaded as the last package
\usepackage[%
    % Any xepersian package option goes here
]{xepersian}
\settextfont{IRXLotus}

  % Any preamble code goes here
  
\begin{document}

  % Demonstration of question here
  
\end{document}
```

**Comment by vafa-khalighi** [comment]
Thanks for your question. The control sequences mentioned in your question works properly with `xepersian` package. In future, please use the [discussion space](https://github.com/tex-persian/xepersian/discussions/categories/q-a) to ask questions about using the package.

I will close this issue as `xepersian` already works as expected in regard to the control sequences `\textbf` and `\textit`. Having said that, if this does not resolve your query, then please use the [discussion space](https://github.com/tex-persian/xepersian/discussions/categories/q-a) to demonstrate your issue and I will be more than happy to help you.
