### ISSUE TITLE
Support cuted package

### ISSUE THREAD

**Issue by bahman-mirzakhani** [tex-persian/xepersian#6]
## Brief outline of the feature request
It will be good if the ```cuted``` package is also supported.

## Check/indicate
- [ ] Relevant to the `bidi` package
- [x] [The `bidi` package issue tracker](https://github.com/tex-persian/bidi/issues) has been searched for similar issues?
- [x] [The `xepersian` package issue tracker](https://github.com/tex-persian/xepersian/issues) has been searched for similar issues?
- [ ] Links to <tex.stackexchange.com> discussion if appropriate
- [ ] Links to <qa.parsilatex.com> discussion if appropriate

## Minimal example

```tex
% !TEX TS-program = XeLaTeX
% !TEX encoding = UTF-8 Unicode


\documentclass[twocolumn]{article}

\usepackage{lipsum}
\usepackage{cuted}

\usepackage{xepersian}
\settextfont{IRXLotus}

\begin{document}
	
	\lipsum[1-2]
	
	\begin{strip} % from cuted package
		\lipsum[4]
	\end{strip}
	
	\lipsum[5-7]
	
\end{document}
```

## Expected behavior
[test.log](https://github.com/tex-persian/xepersian/files/8067641/test.log)

**Comment by vafa-khalighi** [comment]
The `bidi` package already supports the `cuted` package; unless the modifications `bidi` does to `cuted` is outdated.

**Comment by bahman-mirzakhani** [comment]
You are right. The old version of `bidi` have no problem. The MWE in issue have some errors with `bidi` 36.6 and `xepersian` 23.3.
