### ISSUE TITLE
problem-with-parenthesis-of-equation-label in xepersian v23.4

### ISSUE THREAD

**Issue by mdniry** [tex-persian/xepersian#7]
## Brief outline of the issue
I have a problem with the parenthesis of the equation cross-reference. I have this problem even with old files well behaved in the previous versions of xepersian. The problem also extends to the label of the equation when the amsmath package is included.

## Check/indicate
- [x] Relevant to the `bidi` package
- [ ] [The `bidi` package issue tracker](https://github.com/tex-persian/bidi/issues) has been searched for similar issues?
- [ ] [The `xepersian` package issue tracker](https://github.com/tex-persian/xepersian/issues) has been searched for similar issues?
- [ ] Links to <tex.stackexchange.com> discussion if appropriate
- [ ] Links to <qa.parsilatex.com> discussion if appropriate

## Minimal example showing the issue

```tex
% !TEX TS-program = XeLaTeX
% !TEX encoding = UTF-8 Unicode


\documentclass{article}            % or some other class

\usepackage[]{xepersian}
\settextfont{XB Niloofar}
\setmathdigitfont[Scale=1.1]{Yas}
  
\begin{document}

این متن برای بررسی کارکرد درست ارجاع به روابط نوشته شده است~(\ref{eq}) ببینید [مثال دیگر~(\ref{eq})].
\begin{equation}\label{eq}
a = 20.
\end{equation}
  
\end{document}
```

## Expected behavior
این متن برای بررسی کارکرد درست ارجاع به روابط نوشته شده است (۱) ببینید [مثال دیگر (۱)].
a = ۲۰.                                            (۱)

## Log and PDF files 
[main2.pdf](https://github.com/tex-persian/xepersian/files/8083899/main2.pdf)

[main2.log](https://github.com/tex-persian/xepersian/files/8083892/main2.log)

**Comment by vafa-khalighi** [comment]
The `xepersian` package no longer activates Persian Script automatically when using OpenType Render. You need to activate it yourself by simple changing

````tex
\settextfont{XB Niloofar}
````
into
````tex
\settextfont{XB Niloofar}[Script=Persian]
````

**Comment by mdniry** [comment]
با سلام و احترام،

از جواب سریع شما سپاسگزارم.

با تشکر

**Comment by vafa-khalighi** [comment]
The option `Script=Persian` is no longer needed when using OpenType Renderer. I have just uploaded version 23.5 2022-02-20 of `xepersian` package to CTAN which activates Persian Script automatically when using OpenType Render.
