### ISSUE TITLE
how to run xelatex --shell-escape

### ISSUE THREAD

**Issue by nabavi70068** [tex-persian/xepersian#8]
## Check/indicate
- [ ] Relevant to the `bidi` package
- [ ] [The `bidi` package issue tracker](https://github.com/tex-persian/bidi/issues) has been searched for similar issues?
- [ ] [The `xepersian` package issue tracker](https://github.com/tex-persian/xepersian/issues) has been searched for similar issues?
- [ ] Links to <tex.stackexchange.com> discussion if appropriate
- [ ] Links to <qa.parsilatex.com> discussion if appropriate

## Minimal example

```tex
% !TEX TS-program = XeLaTeX
% !TEX encoding = UTF-8 Unicode


\documentclass{article}            % or some other class

  % Any packages other than the xepersian package must be loaded here

  % The xepersian package must be loaded as the last package
\usepackage[%
    % Any xepersian package option goes here
]{xepersian}
\settextfont{IRXLotus}

  % Any preamble code goes here
  
\begin{document}

  % Demonstration of question here
  
\end{document}
```

**Comment by vafa-khalighi** [comment]
Please use the [Discussion Space](https://github.com/tex-persian/xepersian/discussions/categories/q-a) to ask questions in future as the one you are using right now are for issue-related questions. To answer your question, you just need to add `--shell-escape` when running `xelatex`.
